version: 2

models:
  - name: raw_events
    description: "Raw events loaded from JSON source"
    columns:
      - name: event_type
        description: "Type of user interaction (play, pause, seek, complete) - may contain nulls or invalid values"
      - name: user_id
        description: "User identifier - may contain nulls or invalid values"
      - name: episode_id
        description: "Episode identifier - may contain nulls or invalid values"
      - name: timestamp
        description: "ISO timestamp string of the event - may contain nulls or invalid values"
      - name: duration
        description: "Duration in seconds (as string), only for play/complete events - may contain nulls or invalid values"
      - name: filename
        description: "Name of the file from which the record was loaded - not nullable"
        tests:
          - not_null
      - name: load_at
        description: "Timestamp when the record was loaded - not nullable"
        tests:
          - not_null
